INSERT INTO regulations(country, `date`, name) values('Panamá', STR_TO_DATE('06/12/2011', '%d/%m/%Y'), 'Acuerdo No. 006-2011');
INSERT INTO det_regulations(regulations_id, Description) values
(8, 'Se tiene autorización de la Superintendencia de Bancos para operar en Panamá para los canales electrónicos a operar'),
(8, 'Se cuenta con autorización de la Superintendencia de Bancos para incorpor4ar nuevos servicios electrónicos'),
(8, 'Se notifica a la Superintendencia de Bancos la integración de servicios similares a los ya existentes'),
(8, 'Se han sometido los servicios electrónicos a inspecciones por parte de la Superintendencia de Bancos'),
(8, 'Se ha informado a la Superintendencia de Bancos de todos los cajeros automáticos, POS y dispositivos tecnológicos administrados'),
(8, 'Se ha implementado un sistema de gestión de riesgos asociado a las actividades de banca electrónica'),
(8, 'Se establecen responsabilidades específicas, políticas y controles para la gestión de riesgos de los canales electrónicos'),
(8, 'Se revisan y aprueban los aspectos esenciales del proceso de control de riesgos de los canales electrónicos'),
(8, 'Se establecen procesos de diligencia y supervisión para el manejo de relaciones con proveedores externos'),
(8, 'Se asegura de integrar el manual de operaciones las políticas y procedimientos relacionados con la gestión de sus activos tecnológicos'),
(8, 'Se almacena la naturaleza de las transacciones bancarias'),
(8, 'Se cuenta con un sistema de registro de las transacciones y operaciones'),
(8, 'Se cuenta con mecanismos para la supervisión de los riesgos de banca electrónica, sus políticas y controles'),
(8, 'Se cuenta con mecanismos para la evaluación de amenazas, vulnerabilidades e impactos'),
(8, 'Se cuenta con mecanismos para la gestión de incidentes de seguridad para los activos tecnológicos'),
(8, 'Se definen políticas y procedimientos de prevensión aplicables en caso de amenazas tecnológicas potenciales'),
(8, 'Se definen políticas y procedimientos de respuesta aplicables en caso de amenazas tecnológicas potenciales'),
(8, 'Se definen políticas y procedimientos que sean aplicables en caso de violaciones a la seguridad interna y externa a la banca electrónica'),
(8, 'Se definen políticas y procedimientos que incluyan mecanismos de seguridad para la continuidad del negocio'),
(8, 'Se definen mecanismos de diligencia debida y vigilancia de las relaciones con terceros'),
(8, 'Se cuenta con un plan de contiuidad de negocio y recuperación ante desastres'),
(8, 'Se cuenta con un área de rieesgos responsable de la identificación, evaluación y control de riesgos tecnológicos de banca electrónica'),
(8, 'Se realizan auditorias periódicas incorporadas al plan anual de auditoría'),
(8, 'Se cuenta con programas necesarios y personal especializado en el área de auditoría'),
(8, 'Se realizan revisiones externas de riesgo para los canales de banca electrónica'),
(8, 'Se implementan pruebas de intrusión externa por proveedores externos de servicios de seguridad'),
(8, 'Se implementan pruebas de intrusión interna por proveedores externos de servicios de seguridad'),
(8, 'Se realizan pruebas de intrusión por personal interno capacitado'),
(8, 'La información suministrada en internet es adecuada y permite a los clientes identificar al banco'),
(8, 'La información publicada sobre los servicios de banca electrónica es correcta y actualizada'),
(8, 'Se establecen medidas técnicas que aseguran la observancia de las condiciones de privacidad de los clientes y sus operaciones'),
(8, 'Se adoptan medidas de privacidad aplicable a los productos y serviciios de los canales de banca electrónica'),
(8, 'Se establecen programas que garanticen la disponibilidad de los sistemas y servicios de banca electronica'),
(8, 'Se desarrollan planes de respuesta y comunicación de incidentes para la gestión, detención y metigación de fallas de seguridad'),
(8, 'Se cuenta con sistemas de administración para casos de fraude relacionados con los servicios de banca electrónica'),
(8, 'Los sistemas cuentan con un registro de manipulación o alteración de datos con hora y fecha de la operación'),
(8, 'Las bitácoras contienen el registro de acceso a los canales electrónicos, con identificación de usuario y hora de acceso'),
(8, 'Las bitácoras contienen Detalle de las operaciones monetarias realizadas, tales como fecha, hora, canal acceso, monto, cuenta origen y cuenta destino y el tipo de transacción'),
(8, 'Las bitacoras cuentan con datos que permitan realizar investigaciones sobre los canales electrónicos'),
(8, 'La banca por internet cuenta con bitacoras de webserver, el método HTTP, la URI, y el timestamp'),
(8, 'Se lleva un registro de transacciones adecuado al código de comercio'),
(8, 'Se informa al cliente de las características, condiciones y costos del uso de servicios electrónicos'),
(8, 'Se cuenta con DMZ'),
(8, 'Se cuenta con servidor de Logs'),
(8, 'Se cuenta con sistemas IPS o IDS'),
(8, 'Se almacenan los logs de los IPS o IDS por al menos 1 año'),
(8, 'Se cuenta con un método digital para que el cliente pueda identificar el banco al que corresponden sus actividades'),
(8, 'Se comparte al cliente el nombre completo de la cuenta y su última hora de ingreso al servcicio para su conocimiento'),
(8, 'Las plataformas de banca en internet cuentan con contraseñas de como mínimo 8 caracteres'),
(8, 'Las plataformas de banca en internet cuentan con otro factor de autenticación'),
(8, 'Se implementan controles de autenticación para pago móvil'),
(8, 'Se implementan controles de seguridad para proteger la transmisión de la información sensible del cliente en plataformas de pago móvil'),
(8, 'Los cajeros automáticos identifican al cliente a través del número de la tarjeta bancaria'),
(8, 'Los cajeros automáticos cuentan con factor de autenticación de PIN'),
(8, 'Los cajeros automáticos cuentan con un sistema adecuado al circuito integrado'),
(8, 'Los cajeros automáticos cuentan con mecanismos para proteger la información confidencial del cliente'),
(8, 'Los cajeros automáticos cifran las comunicaciones'),
(8, 'Los cajeros automáticos cuentan con cámaras de circuito cerrado y grabación de imagenes'),
(8, 'Se conservan los videos grabados por los cajeros automáticos por 12 meses'),
(8, 'Los POS identifican al cliente a través del número de tarjeta bancaria'),
(8, 'Los POS cuentan con PIN de autenticación'),
(8, 'Los POS cuentan con mecanismos para proteger la información confidencial del cliente'),
(8, 'Los POS cifran las comunicaciones'),
(8, 'Los POS cumplen con medidas de seguridad establecidad para los medios de pago electrónico'),
(8, 'La banca telefónica con audio-respuesta asigna un identificador único de cliente con al menos seis caracteres'),
(8, 'La banca telefónica con audio-respuesta requiere un factor de autenticación con contraseña de al menos seis dígitos para transacciones a terceros'),
(8, 'La banca telefónica voz a voz asigna un identificador único de cliente con al menos seis caracteres'),
(8, 'La banca telefónica voz a voz utiliza cuestionarios para autenticar la información sensible del cliente'),
(8, 'Las redes especializadas emplean certificados digitales para validar la legitimidad de las transacciones'),
(8, 'Las redes especializadas establecen enlaces cifrados con el más alto nivel de seguridad disponible'),
(8, 'Las redes especializadas cuentan con servidores de bastión para proteger los repositorios de información del banco'),
(8, 'Las redes especializadas garantizan la integridad y no repudio de las transacciones'),
(8, 'La mensajería instantánea, redes sociales y correos electrónicos se limitan a suministrar información autorizada por contrato con el cliente'),
(8, 'La banca electrónica verifica la identidad y autorización de nuevos clientes'),
(8, 'La banca electrónica preserva la confidencialidad e integridad de la información transmitida'),
(8, 'La banca electrónica garantiza la no renuncia de transacciones y confirma la ejecución de las mismas'),
(8, 'La banca electrónica segrega responsabilidades para reducir el riesgo de fraude en procesos y sistemas'),
(8, 'La banca electrónica cuenta con una estructura física protegida para servidores y bases de datos'),
(8, 'La banca electrónica mantiene registros de transacciones y asegura su integridad'),
(8, 'La banca electrónica tiene controles internos para la apertura, modificación y cancelación de cuentas'),
(8, 'La banca electrónica asegura la correcta asignación de responsabilidades en caso de irregularidades en el servicio'),
(8, 'Se reportan incidentes de seguridad a la Superintendencia de Bancos'),
(8, 'Se emplean técnicas de control como criptografía para garantizar la privacidad de la información del cliente'),
(8, 'Se instruye a los clientes sobre la protección de su información bancaria personal'),
(8, 'El proveedor de seguridad de la banca electrónica debe contar con personal idóneo y estar autorizado por la Superintendencia'),
(8, 'Se remiten a la Superintendencia reportes relacionados con la banca electrónica'),
(8, 'Se aplican políticas para prevenir el uso indebido de los servicios de banca electrónica'),
(8, 'Se asegura la identificación y seguimiento de transacciones sospechosas en la banca electrónica');
