INSERT INTO regulations(country, `date`,  name) values('Guatemala', STR_TO_DATE('30/11/2022', '%d/%m/%Y'), 'Resolución JM-104-2021');
INSERT INTO det_regulations(regulations_id, `Description`) values
(7, 'Se establecen políticas y procedimientos para administrar el riesgo tecnológico de las instituciones financieras'),
(7, 'Se crean estructuras organizacionales de TI y se capacita al personal'),
(7, 'Se dirige la administración del riesgo tecnológico a través del comité de gestión de riesgos'),
(7, 'Se implementan políticas y procedimientos de administración de riesgo tecnológico'),
(7, 'Se proponen políticas y manuales de administración del riesgo tecnológico'),
(7, 'Se analizan propuestas de políticas y se definen estrategias'),
(7, 'Se revisan las políticas de administración de riesgo'),
(7, 'Se apoya al comité mediante la propuesta de procedimientos y políticas para la administración del riesgo'),
(7, 'Se monitorean y se analizan los riesgos tecnológicos'),
(7, 'Se verifica el nivel de cumplimiento de las políticas y procedimientos'),
(7, 'Se gestiona el acceso y seguridad de bases de datos a través de un administrador'),
(7, 'Se mantiene un esquema actualizado de la interrelación del negocio con la infraestructura de TI'),
(7, 'Se documentan y se implementan procesos operativos para la adquisición, mantenimiento e implementación de sistemas y bases de datos'),
(7, 'Se gestiona adecuadamente los servicios de TI con un catálogo de servicios y acuerdos de niveles de servicio'),
(7, 'Se gestionan incidentes y se implementan procesos de cambio en la infraestructura'),
(7, 'Se documentan metodologías para análisis, diseño, desarrollo, pruebas, puesta en producción, mantenimiento, control de versiones y calidad'),
(7, 'Se gestiona la seguridad de la información para proteger su integridad, confidencialidad y disponibilidad'),
(7, 'Se mitigan riesgos de pérdida, extracción indebida o corrupción de la información'),
(7, 'Se requiere un oficial de seguridad de información para coordinar el cumplimiento de políticas y procedimientos'),
(7, 'Se gestionan incidentes de seguridad de la información'),
(7, 'Se mantienen copias de respaldo de la información considerando periodicidad y procedimientos de restauración'),
(7, 'Se elabora un plan de recuperación ante desastres alineado con el plan de continuidad del negocio'),
(7, 'Se promueven políticas y procedimientos de cultura de seguridad mediante capacitación y concientización'),
(7, 'Se generan políticas y procedimientos para gestionar ciberseguridad, incluyendo funciones de identificación, protección, detección, respuesta y recuperación'),
(7, 'Se desarrollan mecanismos para resistir, responder y recuperarse de ciberataques'),
(7, 'Se monitorean los activos en ciberespacio para detectar vulnerabilidades e incidentes'),
(7, 'Se organizan equipos de respuesta ante incidentes cibernéticos, dirigidos por el oficial de seguridad'),
(7, 'Se implementan planes de recuperación ante desastres que incluyan procedimientos, tiempos de restauración y roles clave'),
(7, 'Se elabora un plan de pruebas de recuperación ante desastres, con alcance, escenarios y periodicidad'),
(7, 'Se capacita al personal clave para ejecutar el plan de acción ante desastres'),
(7, 'Se establece un centro de cómputo alterno para garantizar la continuidad de operaciones'),
(7, 'Se gestionan servicios de terceros mediante políticas de seguridad de información y estándares internacionales'),
(7, 'Se cumplen los requisitos de infraestructura y seguridad para el procesamiento y almacenamiento de información fuera del territorio nacional'),
(7, 'Se cifran las comunicaciones y la información en tránsito y reposo'),
(7, 'Se establecen controles de acceso y autenticidad sin limitaciones legales para auditorías'),
(7, 'Se permite a la Superintendencia de Bancos el acceso libre a la infraestructura y sistemas'),
(7, 'Se contrata personal capacitado localmente para garantizar la continuidad de operaciones'),
(7, 'Se verifica que los proveedores de servicios apliquen políticas de seguridad con certificaciones vigentes'),
(7, 'Se establecen procedimientos para verificar SLA y auditorías independientes de tecnología'),
(7, 'Se garantiza la independencia de la información y la autenticación segura en los servicios contratados'),
(7, 'Se envía a la Superintendencia de Bancos el manual de administración de riesgo tecnológico y el plan de recuperación ante desastres actualizados');
